// ─── Workflow State Machine ─────────────────────────────────────────────
//
// Two-phase pipeline between dev and qa roles:
//   BUILD  phase: dev builds → qa reviews
//   RELEASE phase: dev deploys+publishes → qa confirms
//
// Flow decisions based on QA's output tags:
//   [SUCCESS] → advance to next step / complete
//   [FAILURE] → push back to dev with QA feedback
//   [BLOCKER] → escalate to human via Telegram
//   no tag    → reverify (rerun QA)

import {
  readFileSync,
  writeFileSync,
  appendFileSync,
  existsSync,
  mkdirSync,
  rmSync,
  unlinkSync,
  statSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { join, dirname } from "node:path";

export type Phase = "build" | "release" | "plan";
export type Role = "dev" | "qa";

export interface WorkflowStep {
  phase: Phase;
  step: number;
  role: Role;
  description: string;
}

export interface WorkflowState {
  phase: Phase;
  role: Role; // current active role
  stepIndex: number; // index into STEPS array
  startedAt: number;
  updatedAt: number;
  status: "in_progress" | "completed" | "blocked" | "failed";
  qaOutputFile: string;
  devTaskFile: string;
  qaTaskFile: string;
  confidenceThreshold: number; // min sum (devScore + qaScore) to advance, default 95
  roundsToAdvance: number; // remaining rounds until forced advance, default 10
  context: {
    devScore?: number; // dev's positive confidence (0-100): how well they met requirements
    qaScore?: number; // qa's negative confidence (0-100): how much they doubt quality
    buildResult?: string;
    deployResult?: string;
    publishResult?: string;
    qaFeedback?: string; // last QA message fed back to dev
    notes?: string; // additional workflow context
  };
}

// ─── Workflow Step Definitions ─────────────────────────────────────────

export const WORKFLOW_STEPS: WorkflowStep[] = [
  // PLAN phase
  { phase: "plan", step: 0, role: "dev", description: "Plan the project" },
  { phase: "plan", step: 1, role: "qa", description: "Review plan output" },
  // Transition to RELEASE on [SUCCESS]; on [FAILURE] go back to step 0; on [BLOCKER] escalate

  // BUILD phase
  { phase: "build", step: 0, role: "dev", description: "Build the project" },
  { phase: "build", step: 1, role: "qa", description: "Review build output" },
  // Transition to RELEASE on [SUCCESS]; on [FAILURE] go back to step 0; on [BLOCKER] escalate

  // RELEASE phase
  { phase: "release", step: 0, role: "dev", description: "Deploy and publish" },
  { phase: "release", step: 1, role: "qa", description: "Confirm release" },
  // On [SUCCESS] workflow complete → notify human; on [FAILURE] go back to step 0; on [BLOCKER] escalate
];

export const GITIGNORE_CONTENT = [
  `
  # Auto-generated by pworkflow
  state.json
  task-*.json
  output-qa.txt
`,
].join("\n");
() => PW_DIR();

function ensureDir(): void {
  const dir = PW_DIR();
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

// ─── Read / Write State ─────────────────────────────────────────────────

export function readState(): WorkflowState | null {
  const path = join(PW_DIR(), "state.json");
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return null;
  }
}

export function writeState(state: WorkflowState): void {
  ensureDir();
  state.updatedAt = Date.now();
  const path = join(PW_DIR(), "state.json");
  writeFileSync(path, JSON.stringify(state, null, 2));
}

// ─── Initialise / Reset ─────────────────────────────────────────────────

export function initState(): WorkflowState {
  ensureDir();

  // Create .gitignore in project root to ignore .pworkflow/
  try {
    const rootGitignore = join(process.cwd(), ".gitignore");
    if (!existsSync(rootGitignore)) {
      writeFileSync(rootGitignore, ".pworkflow/\n", "utf-8");
    } else {
      // Ensure .pworkflow/ is listed
      const existing = readFileSync(rootGitignore, "utf-8");
      if (!existing.includes(".pworkflow/")) {
        writeFileSync(rootGitignore, `.pworkflow/\n${existing}`, "utf-8");
      }
    }
  } catch {}

  // Init git repo if not already tracked
  try {
    const gitDir = join(process.cwd(), ".git");
    if (!existsSync(gitDir)) {
      console.log(`[pworkflow] Running git init in ${process.cwd()}`);
      const result = spawnSync("git", ["init"], {
        cwd: process.cwd(),
        stdio: "inherit",
      });
      if (result.status === 0 && existsSync(gitDir)) {
        // Log git init
        const logDir = join(process.cwd(), ".pworkflow");
        if (!existsSync(logDir)) mkdirSync(logDir, { recursive: true });
        const logPath = join(logDir, "git-init.log");
        appendFileSync(
          logPath,
          `${new Date().toISOString()} - git repo initialized in ${process.cwd()}\n`,
        );
      } else {
        console.warn(
          `[pworkflow] git init failed with status ${result.status} or .git not found after init`,
        );
      }
    }
  } catch (err) {
    console.warn(`[pworkflow] Could not run git init: ${err}`);
  }

  const state: WorkflowState = {
    phase: "plan",
    role: "dev",
    stepIndex: 0,
    startedAt: Date.now(),
    updatedAt: Date.now(),
    status: "in_progress",
    qaOutputFile: join(PW_DIR(), "output-qa.txt"),
    devTaskFile: join(PW_DIR(), "task-dev.json"),
    qaTaskFile: join(PW_DIR(), "task-qa.json"),
    confidenceThreshold: 95,
    roundsToAdvance: 10,
    context: {},
  };
  writeState(state);
  return state;
}

export function resetState(): void {
  // Remove all state files for clean restart
  const dir = PW_DIR();
  if (!existsSync(dir)) return;
  try {
    const files = [
      "state.json",
      "task-dev.json",
      "task-qa.json",
      "output-qa.txt",
    ];
    for (const f of files) {
      try {
        try {
          rmSync(join(dir, f));
        } catch {
          try {
            unlinkSync(join(dir, f));
          } catch {}
        }
      } catch {}
    }
  } catch {}
}

// ─── Workflow Queries ───────────────────────────────────────────────────

export function getCurrentStep(state: WorkflowState): WorkflowStep {
  return WORKFLOW_STEPS[state.stepIndex];
}

export function isDevTurn(state: WorkflowState): boolean {
  return state.role === "dev";
}

export function isQaTurn(state: WorkflowState): boolean {
  return state.role === "qa";
}

export function isPlanPhase(state: WorkflowState): boolean {
  return state.phase === "plan";
}

export function isBuildPhase(state: WorkflowState): boolean {
  return state.phase === "build";
}

export function isReleasePhase(state: WorkflowState): boolean {
  return state.phase === "release";
}

export function isWorkflowComplete(state: WorkflowState): boolean {
  return state.status === "completed";
}

export function isWorkflowBlocked(state: WorkflowState): boolean {
  return state.status === "blocked";
}

// ─── Write Task File ────────────────────────────────────────────────────

export function writeTaskFile(role: Role, task: string): void {
  ensureDir();
  const path = join(PW_DIR(), `task-${role}.json`);
  const payload = { task, assignedAt: Date.now() };
  writeFileSync(path, JSON.stringify(payload, null, 2));
}

export function clearTaskFile(role: Role): void {
  const path = join(PW_DIR(), `task-${role}.json`);
  if (existsSync(path)) {
    try {
      unlinkSync(path);
    } catch {}
  }
}

// ─── Read Output File ───────────────────────────────────────────────────

export interface QaOutput {
  status: "success" | "failure" | "blocker" | "unknown";
  body: string;
  mtime: number;
}

/**
 * Parse QA output file looking for predefined tags.
 * Format: first line is tag, rest is message body.
 */
export function readQaOutput(): QaOutput | null {
  const path = join(PW_DIR(), "output-qa.txt");
  if (!existsSync(path)) return null;
  try {
    const content = readFileSync(path, "utf-8");
    const mtime = statSync(path).mtimeMs;
    const lines = content.split("\n");
    const statusLine = (lines[0] || "").trim().toUpperCase();
    const body = lines.slice(1).join("\n").trim();

    let status: QaOutput["status"] = "unknown";
    if (statusLine === "SUCCESS" || statusLine === "[SUCCESS]") {
      status = "success";
    } else if (statusLine === "FAILURE" || statusLine === "[FAILURE]") {
      status = "failure";
    } else if (statusLine === "BLOCKER" || statusLine === "[BLOCKER]") {
      status = "blocker";
    } else {
      // Also check inline in body
      const upper = content.toUpperCase();
      if (upper.includes("[SUCCESS]")) status = "success";
      else if (upper.includes("[FAILURE]")) status = "failure";
      else if (upper.includes("[BLOCKER]")) status = "blocker";
    }

    // Also check body for inline tags
    let cleanedBody = body;
    const inlineTagMatch = cleanedBody.match(/\[(SUCCESS|FAILURE|BLOCKER)\]/i);
    if (inlineTagMatch) {
      status = inlineTagMatch[1].toLowerCase() as QaOutput["status"];
      cleanedBody = cleanedBody
        .replace(/\[(SUCCESS|FAILURE|BLOCKER)\]/gi, "")
        .trim();
    }

    return { status, body: cleanedBody, mtime };
  } catch {
    return null;
  }
}

/**
 * Write the QA output file (used when injecting task context).
 */
export function writeQaOutput(status: string, body: string): void {
  ensureDir();
  const path = join(PW_DIR(), "output-qa.txt");
  const content = `${status}\n${body}`;
  writeFileSync(path, content);
}

// ─── Advance / Fallback / Escalate ──────────────────────────────────────

export function advanceStep(state: WorkflowState): WorkflowState {
  const nextIdx = state.stepIndex + 1;

  if (nextIdx >= WORKFLOW_STEPS.length) {
    state.status = "completed";
    state.role = "qa";
    writeState(state);
    return state;
  }

  const nextStep = WORKFLOW_STEPS[nextIdx];
  if (state.phase === "build" && nextStep.phase === "release") {
    state.phase = "release";
  }

  state.stepIndex = nextIdx;
  state.role = nextStep.role;
  state.roundsToAdvance = (state as any).roundsToAdvance ?? 10; // reset rounds for new step pair
  state.confidenceThreshold = state.confidenceThreshold ?? 95;
  state.qaOutputFile = join(PW_DIR(), "output-qa.txt");
  state.devTaskFile = join(PW_DIR(), "task-dev.json");
  state.qaTaskFile = join(PW_DIR(), "task-qa.json");
  writeState(state);
  return state;
}

/** Force advance past confidence check (max rounds reached). */
export function forceAdvanceStep(state: WorkflowState): WorkflowState {
  const isLastStep =
    state.stepIndex >= WORKFLOW_STEPS.length - 1 ||
    WORKFLOW_STEPS[state.stepIndex + 1] === undefined;
  if (isLastStep) return markCompleted(state);

  const scoreSum =
    (state.context.devScore ?? 0) + Math.min(100, state.context.qaScore ?? 0);
  const maxRounds = (state as any).roundsToAdvance ?? 10;
  console.log(
    `[pworkflow] max rounds reached (${maxRounds}/10), force advancing — sum ${scoreSum} < ${state.confidenceThreshold ?? 95}`,
  );
  state.context.notes = `${state.context.notes || ""}\n[Force-advanced after ${maxRounds} rounds, confidence sum ${scoreSum} < threshold ${state.confidenceThreshold ?? 95}]`;
  return advanceStep(state);
}

export function failBackToDev(
  state: WorkflowState,
  qaFeedback: string,
): WorkflowState {
  state.context.qaFeedback = qaFeedback;

  const scoreSum =
    (state.context.devScore ?? 0) + Math.min(100, state.context.qaScore ?? 0);
  const threshold = state.confidenceThreshold ?? 95;

  // Subtract rounds and check if we hit zero
  const prevToAdvance = (state as any).roundsToAdvance ?? 10;
  const newToAdvance = prevToAdvance - 1;
  if (newToAdvance <= 0) {
    // Max iterations exhausted — force push back to dev
    console.log(
      `[pworkflow] max iterations (${prevToAdvance}) reached after QA failure, pushing back to dev`,
    );
    const phaseSteps = WORKFLOW_STEPS.filter((s) => s.phase === state.phase);
    const devSteps = phaseSteps.filter((s) => s.role === "dev");
    if (devSteps.length > 0) {
      const lastDevStep = devSteps[devSteps.length - 1];
      state.stepIndex = WORKFLOW_STEPS.indexOf(lastDevStep);
    }
    state.role = "dev";
    state.status = "in_progress";
    writeState(state);
    return state;
  }

  (state as any).roundsToAdvance = newToAdvance;
  state.context.notes = `${state.context.notes || ""}\n[Round ${prevToAdvance}/${10}: confidence sum ${scoreSum} < threshold ${threshold}, QA pushed back]`;
  writeState(state);
  return state;
}

/**
 * Mark workflow as blocked (blocker path).
 */
export function markBlocked(
  state: WorkflowState,
  notes?: string,
): WorkflowState {
  state.status = "blocked";
  state.context.notes = notes || "Blocked by QA — human intervention required";
  writeState(state);
  return state;
}

/**
 * Mark workflow as failed.
 */
export function markFailed(
  state: WorkflowState,
  reason?: string,
): WorkflowState {
  state.status = "failed";
  state.context.notes = reason || "Workflow failed";
  writeState(state);
  return state;
}

/**
 * Mark workflow as completed (successful release).
 */
export function markCompleted(state: WorkflowState): WorkflowState {
  state.status = "completed";
  state.context.notes = "Release completed successfully";
  writeState(state);
  return state;
}

export function PW_DIR(): string {
  return join(process.cwd(), ".pworkflow");
}
