// ─── Workflow State Machine ─────────────────────────────────────────────
//
// Two-phase pipeline between dev and qa roles:
//   BUILD  phase: dev builds → qa reviews
//   RELEASE phase: dev deploys+publishes → qa confirms
//
// Flow decisions based on QA's output tags:
//   [SUCCESS] → advance to next step / complete
//   [FAILURE] → push back to dev with QA feedback
//   [BLOCKER] → escalate to human via Telegram
//   no tag    → reverify (rerun QA)

import {
  readFileSync,
  writeFileSync,
  appendFileSync,
  existsSync,
  mkdirSync,
  unlinkSync,
  statSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { debugLog } from "./logger";

export type Phase = "build" | "release" | "plan" | "divide";
export type PlanPhaseMode = "initial" | "iteration" | "done";
export type Role = "dev" | "qa";

/** Default combined score threshold (devScore + qaScore), max 200. */
export const DEFAULT_CONFIDENCE_THRESHOLD = 180;
export const DEFAULT_ROUND_TO_ADVANCE = 10;

export interface WorkflowPhase {
  phase: Phase;
  description: string;
}

export interface WorkflowState {
  phase: Phase;
  role: Role; // current active role
  nextRole: Role;
  stepIndex: number; // index into STEPS array
  startedAt: number;
  updatedAt: number;
  status: "in_progress" | "completed" | "blocked" | "failed";
  devOutputFile: string; // dev writes work product here (read by QA)
  qaOutputFile: string; // QA writes review feedback here (read by dev)
  devTaskFile: string;
  qaTaskFile: string;
  confidenceThreshold: number; // min sum (devScore + qaScore, max 200) to advance. Defaults to DEFAULT_CONFIDENCE_THRESHOLD
  roundsToAdvance: number; // remaining rounds until forced advance, default 10
  currentSubtaskIndex?: number; // for build phase: which subtask we're on (0-based)
  subtasksCompleted?: number[]; // list of completed subtask indices
  roleModels?: {
    dev?: string; // model ID for dev role (e.g. "anthropic/claude-sonnet-4-5")
    qa?: string; // model ID for QA role
  };
  context: {
    devScore?: number; // dev's positive confidence (0-100): how well they met requirements
    qaScore?: number; // qa's negative confidence (0-100): how much they doubt quality
    buildResult?: string;
    deployResult?: string;
    publishResult?: string;
    qaFeedback?: string; // last QA message fed back to dev
    notes?: string; // additional workflow context
    humanGoal?: string; // human goal for the current task
    lastAgentMessage?: string; // last agent message (for error reporting)
  };
}

// ─── Workflow Step Definitions ─────────────────────────────────────────

export const WORKFLOW_PHASES: WorkflowPhase[] = [
  {
    phase: "plan",
    description:
      "Plan phase: dev researches plan for human goal, qa validates.\n" +
      "- Dev produces a plan outline with clear steps to achieve the human's goal.\n" +
      "- If plan exceeds 8k tokens, split into parts (plan-part1.md, plan-part2.md...).\n" +
      "- For multi-part plans: dev writes summary.md combining key points and per-part scores (0-100 each).\n" +
      "- QA reviews the summary (and all parts if needed within token budget), finds missing parts or ambiguities.\n" +
      "- QA scores confidence in the overall plan on scale 0-100.",
  },

  {
    phase: "divide",
    description:
      "Divide phase: dev breaks plan into subtasks, qa validates scope.\n" +
      "- Dev breaks the plan into smaller actionable tasks, each under 8k token budget.\n" +
      "- Dev writes each task in a separate document in the doc folder with numbered filenames (task-001.md, task-002.md...).\n" +
      "- Dev records execution order in .pworkflow/task-order.json (ordered list of filenames).\n" +
      "- QA verifies tasks are written in executable order and matches the recorded order.\n" +
      "- Dev scores completeness of the subtask division on scale 0-100.\n" +
      "- QA checks for gaps, dependencies, feasibility, and token budget compliance.\n" +
      "- QA scores confidence in the division plan on scale 0-100.",
  },

  {
    phase: "build",
    description:
      "Build phase: dev implements subtask, qa reviews.\n" +
      "- Dev completes the subtask (output under 8k tokens) and scores completeness on scale 0-100.\n" +
      "- QA verifies the implementation, scores confidence 0-100.",
  },

  {
    phase: "release",
    description:
      "Release phase: dev deploys to production, qa confirms readiness.\n" +
      "- Dev deploys/publishes changes to railway production (output under 8k tokens).\n" +
      "- Dev scores deployment success on scale 0-100.\n" +
      "- QA runs final checks, confirms no blockers.\n" +
      "- QA scores confidence in the release on scale 0-100.",
  },
];

export const GITIGNORE_CONTENT = [
  `
  # Auto-generated by pworkflow
  .pworkflow/*
  .pworkflow/task-*.json
  .pworkflow/output-*.txt
`,
].join("\n");
() => PW_DIR();

function ensureDir(): void {
  const dir = PW_DIR();
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

// ─── Read / Write State ─────────────────────────────────────────────────

const STATE_FILE = "state.json";

// Old broken path from prior versions — migrate on read
// Bug: readState/writeState used join(PW_DIR(), ".pworkflow/*") = .pworkflow/.pworkflow/*
function oldStatePath(): string {
  return join(PW_DIR(), ".pworkflow", "*");
}

export function readState(): WorkflowState | null {
  const path = join(PW_DIR(), STATE_FILE);
  if (!existsSync(path)) {
    // Migrate state from old broken path (.pworkflow/.pworkflow/*)
    const oldPath = oldStatePath();
    if (existsSync(oldPath)) {
      try {
        const data = readFileSync(oldPath, "utf-8");
        const state = JSON.parse(data) as WorkflowState;
        writeState(state); // write to new correct path
        try {
          unlinkSync(oldPath);
        } catch {} // remove old
        return state;
      } catch {}
    }
    return null;
  }
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return null;
  }
}

export function writeState(state: WorkflowState): void {
  ensureDir();
  state.updatedAt = Date.now();
  const path = join(PW_DIR(), STATE_FILE);
  writeFileSync(path, JSON.stringify(state, null, 2));
}

// ─── Initialise / Reset ─────────────────────────────────────────────────

export function initState(): WorkflowState {
  ensureDir();

  // Preserve roleModels from existing state so model config survives re-init
  const existing = (() => {
    try {
      return readState();
    } catch {
      return null;
    }
  })();
  const roleModels = existing?.roleModels ?? {};
  const context = existing?.context ?? {};

  // Init git repo if not already tracked
  try {
    const gitDir = join(process.cwd(), ".git");
    if (!existsSync(gitDir)) {
      console.log(`[pworkflow] Running git init in ${process.cwd()}`);
      const result = spawnSync("git", ["init"], {
        cwd: process.cwd(),
        stdio: "inherit",
        timeout: 10_000, // 10s timeout to prevent freezing
      });
      if (result.status === 0 && existsSync(gitDir)) {
        // Log git init
        const logDir = join(process.cwd(), ".pworkflow");
        if (!existsSync(logDir)) mkdirSync(logDir, { recursive: true });
        const logPath = join(logDir, "git-init.log");
        appendFileSync(
          logPath,
          `${new Date().toISOString()} - git repo initialized in ${process.cwd()}\n`,
        );
      } else {
        console.warn(
          `[pworkflow] git init failed with status ${result.status} or .git not found after init`,
        );
      }
    }
  } catch (err) {
    console.warn(`[pworkflow] Could not run git init: ${err}`);
  }

  const state: WorkflowState = {
    phase: "plan",
    role: "dev",
    nextRole: "qa",
    stepIndex: 0,
    startedAt: Date.now(),
    updatedAt: Date.now(),
    status: "in_progress",
    devOutputFile: join(PW_DIR(), "output-dev.txt"),
    qaOutputFile: join(PW_DIR(), "output-qa.txt"),
    devTaskFile: join(PW_DIR(), "task-dev.json"),
    qaTaskFile: join(PW_DIR(), "task-qa.json"),
    confidenceThreshold: DEFAULT_CONFIDENCE_THRESHOLD,
    roundsToAdvance: DEFAULT_ROUND_TO_ADVANCE,
    roleModels,
    context,
  };
  writeState(state);
  return state;
}

export function getRoleModel(
  role: Role,
  state: WorkflowState,
): string | undefined {
  return state.roleModels?.[role];
}

export function setRoleModel(
  role: Role,
  modelId: string,
  state: WorkflowState,
): void {
  if (!state.roleModels) state.roleModels = {};
  state.roleModels[role] = modelId;
  writeState(state);
}

export function resetState(): void {
  const pwDir = PW_DIR();

  // Delete stale output files so fresh workflow starts clean
  for (const f of [
    "output-dev.txt",
    "output-qa.txt",
    "task-dev.json",
    "task-qa.json",
  ]) {
    const fp = join(pwDir, f);
    if (existsSync(fp)) {
      try {
        unlinkSync(fp);
      } catch {}
    }
  }

  try {
    // Preserve roleModels AND context from existing state
    const existing = readState();
    const roleModels = existing?.roleModels ?? {};
    const context = existing?.context ?? {};

    const state: WorkflowState = {
      phase: "plan",
      role: "dev",
      nextRole: "qa",
      stepIndex: 0,
      startedAt: Date.now(),
      updatedAt: Date.now(),
      status: "in_progress",
      devOutputFile: join(pwDir, "output-dev.txt"),
      qaOutputFile: join(pwDir, "output-qa.txt"),
      devTaskFile: join(pwDir, "task-dev.json"),
      qaTaskFile: join(pwDir, "task-qa.json"),
      confidenceThreshold: DEFAULT_CONFIDENCE_THRESHOLD,
      roundsToAdvance: 10,
      roleModels,
      context,
    };
    writeState(state);
  } catch {}
}

// ─── Workflow Queries ───────────────────────────────────────────────────

export function getCurrentStep(state: WorkflowState): WorkflowPhase {
  return WORKFLOW_PHASES[state.stepIndex];
}

export function isDevTurn(state: WorkflowState): boolean {
  return state.role === "dev";
}

export function isQaTurn(state: WorkflowState): boolean {
  return state.role === "qa";
}

export function isPlanPhase(state: WorkflowState): boolean {
  return state.phase === "plan";
}

export function isBuildPhase(state: WorkflowState): boolean {
  return state.phase === "build";
}

export function isReleasePhase(state: WorkflowState): boolean {
  return state.phase === "release";
}

export function isWorkflowComplete(state: WorkflowState): boolean {
  return state.status === "completed";
}

export function isWorkflowBlocked(state: WorkflowState): boolean {
  return state.status === "blocked";
}

// ─── Write Task File ────────────────────────────────────────────────────

export function writeTaskFile(role: Role, task: string): void {
  ensureDir();
  const path = join(PW_DIR(), `task-${role}.json`);
  const payload = { task, assignedAt: Date.now() };
  writeFileSync(path, JSON.stringify(payload, null, 2));
}

export function clearTaskFile(role: Role): void {
  const path = join(PW_DIR(), `task-${role}.json`);
  if (existsSync(path)) {
    try {
      unlinkSync(path);
    } catch {}
  }
}

// ─── Read Output File ───────────────────────────────────────────────────

export interface QaOutput {
  status: "success" | "failure" | "blocker" | "unknown";
  body: string;
  mtime: number;
}

/**
 * Parse QA output file looking for predefined tags.
 * Format: first line is tag, rest is message body.
 */
export function readQaOutput(): QaOutput | null {
  const path = join(PW_DIR(), "output-qa.txt");
  if (!existsSync(path)) return null;
  try {
    const content = readFileSync(path, "utf-8");
    const mtime = statSync(path).mtimeMs;
    const lines = content.split("\n");
    const statusLine = (lines[0] || "").trim().toUpperCase();
    const body = lines.slice(1).join("\n").trim();

    let status: QaOutput["status"] = "unknown";
    if (statusLine === "SUCCESS" || statusLine === "[SUCCESS]") {
      status = "success";
    } else if (statusLine === "FAILURE" || statusLine === "[FAILURE]") {
      status = "failure";
    } else if (statusLine === "BLOCKER" || statusLine === "[BLOCKER]") {
      status = "blocker";
    } else {
      // Also check inline in body
      const upper = content.toUpperCase();
      if (upper.includes("[SUCCESS]")) status = "success";
      else if (upper.includes("[FAILURE]")) status = "failure";
      else if (upper.includes("[BLOCKER]")) status = "blocker";
    }

    // Also check body for inline tags
    let cleanedBody = body;
    const inlineTagMatch = cleanedBody.match(/\[(SUCCESS|FAILURE|BLOCKER)\]/i);
    if (inlineTagMatch) {
      status = inlineTagMatch[1].toLowerCase() as QaOutput["status"];
      cleanedBody = cleanedBody
        .replace(/\[(SUCCESS|FAILURE|BLOCKER)\]/gi, "")
        .trim();
    }

    return { status, body: cleanedBody, mtime };
  } catch {
    return null;
  }
}

/**
 * Write the QA output file (used when injecting task context).
 */
export function writeQaOutput(status: string, body: string): void {
  ensureDir();
  const path = join(PW_DIR(), "output-qa.txt");
  const content = `${status}\n${body}`;
  writeFileSync(path, content);
}

// ─── Advance / Fallback / Escalate ──────────────────────────────────────

export function advancePhase(state: WorkflowState): WorkflowState | null {
  debugLog("### advancePhase", state);
  const currentPhase = state.phase;
  if (state.stepIndex + 1 < WORKFLOW_PHASES.length) {
    var newPhase = WORKFLOW_PHASES[state.stepIndex].phase;
    while (newPhase === currentPhase) {
      state.stepIndex++;
      newPhase = WORKFLOW_PHASES[state.stepIndex].phase;
    }
    state.phase = newPhase;
    state.status = "in_progress";
    state.roundsToAdvance = DEFAULT_ROUND_TO_ADVANCE;
    state.nextRole = "dev";
    state.context.devScore = 0;
    state.context.qaScore = 0;

    debugLog(`[advancePhase] switching to dev role`);
    writeState(state);
  } else {
    return null;
  }
  return state;
}

export function failBackToDev(
  state: WorkflowState,
  qaFeedback: string,
): WorkflowState {
  state.context.qaFeedback = qaFeedback;

  const scoreSum =
    (state.context.devScore ?? 0) + Math.min(100, state.context.qaScore ?? 0);
  const threshold = state.confidenceThreshold ?? DEFAULT_CONFIDENCE_THRESHOLD;

  // Subtract rounds and check if we hit zero
  const prevToAdvance = (state as any).roundsToAdvance ?? 10;
  const newToAdvance = prevToAdvance - 1;
  if (newToAdvance <= 0) {
    // Max iterations exhausted — force push back to dev
    console.log(
      `[pworkflow] max iterations (${prevToAdvance}) reached after QA failure, pushing back to dev`,
    );
    state.role = "dev";
    debugLog(`[fallBackToDev] 11 switching to dev role`);
    state.status = "in_progress";
    writeState(state);
    return state;
  }

  (state as any).roundsToAdvance = newToAdvance;
  state.context.notes = `${state.context.notes || ""}\n[Round ${prevToAdvance}/${10}: confidence sum ${scoreSum} < threshold ${threshold}, QA pushed back]`;

  // Push back to dev — reset step index to start of phase and set role to dev
  state.role = "dev";
  debugLog(`[fallBackToDev] 22 switching to dev role`);
  state.status = "in_progress";
  writeState(state);
  return state;
}

/**
 * Mark workflow as blocked (blocker path).
 */
export function markBlocked(
  state: WorkflowState,
  notes?: string,
): WorkflowState {
  state.status = "blocked";
  state.context.notes = notes || "Blocked by QA — human intervention required";
  writeState(state);
  return state;
}

/**
 * Mark workflow as failed.
 */
export function markFailed(
  state: WorkflowState,
  reason?: string,
): WorkflowState {
  state.status = "failed";
  state.context.notes = reason || "Workflow failed";
  writeState(state);
  return state;
}

/**
 * Mark workflow as completed (successful release).
 */
export function markCompleted(state: WorkflowState): WorkflowState {
  state.status = "completed";
  state.context.notes = "Release completed successfully";
  writeState(state);
  return state;
}

/**
 * Mark plan phase as complete (threshold met, ready to advance).
 */
export function markPlanPhaseComplete(state: WorkflowState): WorkflowState {
  state.status = "in_progress";
  state.phase = "build";
  state.context.notes =
    "Plan phase complete - score threshold met" +
    `\nDev score: ${state.context.devScore ?? 0}` +
    `\nQA score: ${state.context.qaScore ?? 0}`;
  writeState(state);
  return state;
}

/**
 * For build phase with subtasks: load task order from .pworkflow/task-order.json.
 * Returns array of subtask filenames in execution order, or null if not available.
 */
export function getSubtaskOrder(): string[] | null {
  const path = join(PW_DIR(), "task-order.json");
  if (!existsSync(path)) return null;
  try {
    const data = readFileSync(path, "utf-8");
    return JSON.parse(data);
  } catch {
    return null;
  }
}

/**
 * Get the current subtask filename for build phase.
 */
export function getCurrentSubtask(state: WorkflowState): string | null {
  const order = getSubtaskOrder();
  if (!order) return null;

  const currentIndex = state.currentSubtaskIndex ?? 0;
  if (currentIndex >= order.length) return null;

  return order[currentIndex];
}

/**
 * Mark current subtask as complete and advance to next subtask in build phase.
 * Returns true if there are more subtasks, false if all done.
 */
export function advanceSubtask(state: WorkflowState): boolean {
  if (state.phase !== "build") return false;

  const order = getSubtaskOrder();
  if (!order) return false;

  // Track completion
  if (!state.subtasksCompleted) state.subtasksCompleted = [];
  state.subtasksCompleted.push(state.currentSubtaskIndex ?? 0);

  // Advance to next subtask
  let newIndex = (state.currentSubtaskIndex ?? 0) + 1;

  if (newIndex >= order.length) {
    // All subtasks complete - advance to release phase
    advancePhase(state);
    state.currentSubtaskIndex = undefined;
    writeState(state);
    return false; // no more subtasks in build
  }

  state.currentSubtaskIndex = newIndex;
  state.nextRole = "dev";
  debugLog(`[advanceSubtask] switching to dev role`);
  writeState(state);
  return true; // more subtasks to do
}

/**
 * Reset subtask tracking for new build phase (when entering build from divide).
 */
export function resetBuildTracking(state: WorkflowState): void {
  const order = getSubtaskOrder();
  if (!order || order.length === 0) return;

  state.currentSubtaskIndex = 0;
  state.subtasksCompleted = [];
  writeState(state);
}

export function PW_DIR(): string {
  return join(process.cwd(), ".pworkflow");
}

/**
 * Get total number of subtasks and completed count from workflow state.
 */
export function getSubtaskProgress(state: WorkflowState): {
  total: number;
  completed: number;
} {
  const order = getSubtaskOrder();
  if (!order) return { total: 0, completed: 0 };

  const completed = state.subtasksCompleted?.length ?? 0;
  const current = state.currentSubtaskIndex ?? 0;
  // Include the current subtask as in-progress
  const total = order.length;
  return {
    total,
    completed: Math.min(completed + (current > 0 ? 1 : 0), total),
  };
}

/** Sync the mtime of a task file to prevent re-firing pollers. */
export function syncTaskFileMtime(role: "dev" | "qa"): void {
  const taskFile = role === "qa" ? "task-qa.json" : "task-dev.json";
  const taskPath = join(PW_DIR(), taskFile);
  try {
    if (existsSync(taskPath)) {
      const st = statSync(taskPath);
      // Re-write file to update mtime
      const data = readFileSync(taskPath);
      writeFileSync(taskPath, data);
    }
  } catch {}
}
